config/routes.rb
Rails.application.routes.draw do
  root to: redirect('http://intro.parti.xyz/')
  sso_devise

  resources :issues do

  end

  resources :positions do
    shallow do
      resources :opinions do
        resources :likes, except: :destory do
          collection do
            delete :by_me, to: 'likes#destroy_by_me'
          end
        end
      end
      resources :votes
    end
  end

  resources :supports do
    collection do
      delete :cancel
    end
  end
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  include Chociable

  belongs_to :user
  belongs_to :position
  has_many :likes, dependent: :destroy, counter_cache: true
  belongs_to :source, class_name: Opinion, foreign_key: :source_id
  has_many :response, class_name: Opinion, source: :source, foreign_key: :source_id
  has_many :activities, as: :trackable

  def liked_by? user
    likes.exists?(user: user)
  end

  def best?
    position.opinions.best? self
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource :position
  load_and_authorize_resource :opinion, through: :position, shallow: true

  def new
  end

  def create
    @opinion.user = current_user

    @vote = @opinion.position.voted_by current_user
    @opinion.choice = @vote.try(:choice)

    if @opinion.save
      Activity.create(position: @opinion.position, trackable: @opinion, user: current_user, key: 'create_opinion')
      redirect_to @opinion.position
    else
      render 'new'
    end
  end

  def update
    @opinion.update_attributes(opinion_params)
    redirect_to @opinion.position
  end

  def destroy
    @opinion.destroy
    redirect_to @opinion.position
  end

  private

  def opinion_params
    params.require(:opinion).permit(:body, :source_id)
  end
end

app/views/opinions/_form.html.haml
= form_for [@position, @opinion] do |f|
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  = f.submit '저장', class: 'btn btn-default'

app/views/opinions/_opinion.html.haml
%li.media[opinion]{ style: 'margin-bottom: 30px; '}
  .media-left
    %a(href="#" style='position: relative')
      - if opinion.user.leader_of? current_user
        %span.label.label-success(style='position: absolute; z-index: 10') 지지
      = image_tag opinion.user.image_url, class: 'media-object img-circle', style: 'width:64px;height:64px;'
    %p.text-center.text-muted
      %small
        = choice_icon(opinion)
        = opinion.choice_text
  .media-body
    %h5.media-heading
      %strong= opinion.user.nickname
      %span.text-muted
        = date_f opinion.created_at
        - if can? :edit, opinion
          = link_to [:edit, opinion] do
            %i.fa.fa-edit
        - if can? :destroy, opinion
          = link_to opinion, method: :delete, data: { confirm: '정말 삭제하시겠습니까?'} do
            %i.fa.fa-trash

    %div
      = simple_format opinion.body
      - if opinion.source.present?
        %blockquote.text-muted(style='font-size: inherit;')
          = user_byline(opinion.source.user)
          = date_f opinion.source.created_at
          = simple_format (truncate(opinion.source.body) { link_to "더보기", "#" })
    %div.text-muted
      - if opinion.best?
        %span.label.label-success 베스트
      %sapn(style='margin-right: 10px')
        - if user_signed_in? and opinion.user != current_user
          - if opinion.liked_by? current_user
            = link_to by_me_opinion_likes_path(opinion), method: :delete, style: 'text-decoration: none' do
              %span.change-icon
                %i.fa.fa-heart
                %i.fa.fa-heartbeat
              - preview_count = 3
              - opinion.likes.limit(preview_count).each do |like|
                = user_byline_tiny(like.user)
              - if opinion.likes.count > preview_count
                \+
                = link_to '#' do
                  #{opinion.likes.count - preview_count}
          - else
            = link_to opinion_likes_path(opinion), method: :post, style: 'text-decoration: none' do
              %span.change-icon
                %i.fa.fa-heart-o
                %i.fa.fa-heart
              - preview_count = 3
              - opinion.likes.limit(preview_count).each do |like|
                = user_byline_tiny(like.user)
              - if opinion.likes.count > preview_count
                \+
                = link_to '#' do
                  #{opinion.likes.count - preview_count}
        - else
          %i.fa.fa-heart
          - preview_count = 3
          - opinion.likes.limit(preview_count).each do |like|
            = user_byline_tiny(like.user)
          - if opinion.likes.count > preview_count
            \+
            = link_to '#' do
              #{opinion.likes.count - preview_count}
        = '0' if opinion.likes.count == 0
      - if can? :respond, opinion
        %span
          %a(href="#" data-toggle='catan-opinion-respond' data-source-id="#{opinion.id}" data-form="#new_opinion" data-source-user-nickname="#{opinion.user.nickname}")<
            %i.fa.fa-comment
          = opinion.response.count
      - else
        %span
          %i.fa.fa-comment
          = opinion.response.count

app/views/opinions/edit.html.haml
.container
  %h3 의견 수정
  = render 'form'

app/views/opinions/new.html.haml
.container
  %h3 의견 생성
  = render 'form'