config/routes.rb
Rails.application.routes.draw do
  root to: redirect('http://intro.parti.xyz/')
  sso_devise

  resources :issues do

  end

  resources :positions do
    shallow do
      resources :opinions do
        resources :likes, except: :destory do
          collection do
            delete :by_me, to: 'likes#destroy_by_me'
          end
        end
      end
      resources :votes
    end
  end

  resources :supports do
    collection do
      delete :cancel
    end
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :user
  belongs_to :issue
  has_many :opinions do
    %w(agree disagree).each do |choice|
      define_method "#{choice}_maximum_likes_count" do
        where(choice: choice).maximum(:likes_count)
      end

      define_method "#{choice}_minimum_likes_count" do
        where(choice: choice).minimum(:likes_count)
      end

      define_method "#{choice}_best" do
        where(choice: choice)
        .where(likes_count: send(:"#{choice}_maximum_likes_count"))
        .where.not(likes_count: send(:"#{choice}_minimum_likes_count"))
      end
    end

    def best
      unscoped.where.any_of(agree_best, disagree_best).order(likes_count: :desc).order(created_at: :desc)
    end

    def not_best
      none_of(agree_best, disagree_best).order(created_at: :desc)
    end

    def best? opinion
      maximum_likes_count = try(:"#{opinion.choice}_maximum_likes_count")
      minimum_likes_count = try(:"#{opinion.choice}_minimum_likes_count")
      return false if maximum_likes_count == minimum_likes_count
      return opinion.likes_count >= maximum_likes_count
    end
  end
  has_many :votes do
    def by_leaders_of(user)
      where(user: user.leaders)
    end

    def by_leaders_me(user)
      where(user: [user.leaders, user].flatten)
    end

    %w(agree disagree).each do |choice|
      define_method "#{choice}_percent" do
        choice_count = where(choice: choice).count.to_f
        total_count = where(choice: %w(agree disagree)).count.to_f
        (100 *  choice_count / total_count).round
      end
    end
  end

  has_many :activities

  scope :touched_by_leaders_of, -> (user) { includes(:activities).references(:activities).where(activities: { user: user.leaders }).order('activities.created_at desc') }
  def voted_by voter
    votes.where(user: voter).first
  end

  def voted? voter
    votes.exists? user: voter
  end

  def agreed? voter
    votes.exists? user: voter, choice: 'agree'
  end

  def disagreed? voter
    votes.exists? user: voter, choice: 'disagree'
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource

  def index
    if user_signed_in? and current_user.leaders.any?
      @positions_touched_by_leaders = Position.touched_by_leaders_of(current_user)
    end

    @positions = Position.order(created_at: :desc)
  end

  def show
    render stauts: 404 and return if @position.nil?
    render 'show'
  end

  def new
  end

  def edit
  end

  def create
    set_issue
    @position.user = current_user

    if @position.save
      Activity.create(position: @position, trackable: @position, user: current_user, key: 'create_position')
      redirect_to @position
    else
      render 'new'
    end
  end

  def update
    @position.assign_attributes(position_params)
    set_issue
    if @position.save
      redirect_to @position
    else
      render 'edit'
    end
  end

  def destroy
    @position.destroy
    redirect_to positions_path
  end

  private

  def position_params
    params.require(:position).permit(:body)
  end

  def set_issue
    @position.issue = Issue.find_or_create_by({title: params[:issue_title]}) do |issue|
      issue.user = current_user
    end
  end

end

app/views/positions/_form.html.haml
= form_for @position do |f|
  .form-group
    %p 나는
  .form-group
    %p
      %input.typeahead{ type: 'text', placeholder: '이슈', data: { 'provider': 'typeahead', 'typeahead-url': issues_path, 'typeahead-display-field': 'title' }, name: 'issue_title', value: @position.issue.try(:title) }
      에 관하여
  .form-group
    = f.text_area :body, class: 'form-control'
    %p 이란 입장에
  .form-group
    %p
      %select(class='form-control' style='width: 100px')
        %option{:value => "찬성", selected: :selected } 찬성
        %option{:value => "반대"} 반대
      합니다

  %hr

  .form-group
    %p 왜냐하면
    = text_area_tag :opinion, '', class: 'form-control'

  = f.submit '입장 저장하기', class: 'btn btn-lg btn-primary'

app/views/positions/_position.html.haml
.col-sm-4.col-xs-6
  .thumbnail.canoe[position]
    .caption
      %h4
        “
        = link_to position.body, position
        ”
      %p= position.user.nickname
      - unless current_user == position.user
        - if position.user.leader_of?(current_user)
          지지 중입니다.
          = link_to '지지철회하기', cancel_supports_path(leader_id: position.user), method: :delete
        - else
          = link_to '지지하기', supports_path(support: { leader_id: position.user.id }), method: :post
      - if local_assigns[:activities_concerned] and local_assigns[:activities_concerned].any?
        %hr
        - if activities_concerned.of_agree.any?
          %h5 찬성
          - activities_concerned.of_agree.each do |activity|
            @#{activity.trackable.user.nickname}
        - if activities_concerned.of_disagree.any?
          %h5 반대.
          - activities_concerned.of_disagree.each do |activity|
            @#{activity.trackable.user.nickname}
        - if activities_concerned.of_opinion.any?
          %h5 의견
          %ul
            - activities_concerned.of_opinion.each do |activity|
              %li
                = activity.trackable.body
                @#{activity.trackable.user.nickname}

app/views/positions/_position_header.html.haml
%section#section-show-position-header
  .container
    .jumbotron
      .actions.pull-right
        %small
          = user_byline @position.user
          - if can? :edit, @position
            = link_to [:edit, @position] do
              %i.fa.fa-edit
              수정
          - if can? :destroy, @position
            = link_to @position, method: :delete do
              %i.fa.fa-trash
              삭제

      .position-header-title{ style: 'font-weight: bold; padding: 0; margin-top: 40px; margin-bottom: 50px;' }
        %h4.text-center= link_to @position.issue.title, @position.issue
        %h2.text-center
          “
          = @position.body
          ”

      - unless @position.voted?(current_user)
        .vote-box.text-center
          = link_to position_votes_path(@position, vote: { choice: :agree }), method: :post, class: 'btn btn-default' do
            = choice_icon(:agree)
            찬성
          = link_to position_votes_path(@position, vote: { choice: :disagree }), method: :post, class: 'btn btn-default' do
            = choice_icon(:disagree)
            반대
          %div{ style: 'margin-top: 10px;' }
            = link_to '잘 모르겠어요', '#', class: 'text-muted'

      - if @position.voted?(current_user)
        .result-box.text-center(style="margin-top: 50px")
          %ul.nav.nav-tabs(role="tablist")
            %li(class="#{'active' if current_user.leaders.any?}" role="presentation" style="width:50%")
              %a(href="#result-leaders" role="tab" data-toggle="tab")
                %i.fa.fa-users
                내가 지지하는 사람들
            %li(class="#{'active' if current_user.leaders.empty?}" style="width:50%")
              %a(href="#result-anonymous" role="tab" data-toggle="tab")
                %i.fa.fa-cloud
                모든 사람들
          .tab-content
            .tab-pane#result-leaders(class="#{'active' if current_user.leaders.any?}" role="tabpanel")
              .row
                - if current_user.leaders.any?
                  .col-xs-6
                    %h5
                      = choice_icon(:agree)
                      찬성
                      .lead
                        %strong= @position.votes.by_leaders_me(current_user).agree_percent
                        \%
                    - @position.votes.agree.by_leaders_me(current_user).each do |vote|
                      = user_byline vote.user
                  .col-xs-6
                    %h5
                      = choice_icon(:disagree)
                      반대
                      .lead
                        %strong= @position.votes.by_leaders_me(current_user).disagree_percent
                        \%
                    - @position.votes.disagree.by_leaders_me(current_user).each do |vote|
                      = user_byline vote.user
                - else
                  .col-xs-12
                    %div(style='margin-top: 20px') 아직 지지하는 사람이 없습니다.
                    %a(href="#") 지지할 사람 찾기
            .tab-pane#result-anonymous(class="#{'active' if current_user.leaders.empty?}" role="tabpanel")
              .row
                .col-xs-6
                  %h5
                    = choice_icon(:agree)
                    찬성
                    .lead
                      %strong= @position.votes.agree.count
                  - @position.votes.agree.each do |vote|
                    = user_byline vote.user
                .col-xs-6
                  %h5
                    = choice_icon(:disagree)
                    반대
                    .lead
                      %strong= @position.votes.disagree.count
                  - @position.votes.disagree.each do |vote|
                    = user_byline vote.user

      %div(style='width: 100%; min-height: 5em;')
        - 20.times.each do
          %div(style='min-width: 5%; height: 5em; position: relative; float:left;')
            - agree_height = "1.#{[1,2,3,4,5,6].sample}"
            - disagree_height = "1.#{[6,3,2,4,1,8].sample}"
            %div(style='min-height: #{agree_height}em; background-color: #cfcfcf; width: 90%; position: absolute; bottom: #{disagree_height}em; right: 5%;')
            %div(style='min-height: #{disagree_height}em; background-color: #bfbfbf; width: 90%; position: absolute; bottom: 0; right: 5%;')

app/views/positions/edit.html.haml
.container
  %h3 입장 수정
  = render 'form'

app/views/positions/index.html.haml
.bs-component
  .container
    - if user_signed_in?
      .jumbotron
        .text-center
          %h3
            민주주의는 서로의 입장을 확인하면서 시작됩니다.

          %p= link_to '투표 만들기', new_position_path, class: 'btn btn-primary btn-lg'


    - {by_leaders: @positions_touched_by_leaders, all: @positions}.each do |key, positions|
      - if positions
        .page-header
          %h3= { by_leaders: '지지하는 사람들의 최근 활동', all: '최근 투표' }[key]
        .row.position-list
          - positions.each do |position|
            - if key == :by_leaders
              = render position, activities_concerned: position.activities.concerned_by(current_user)
            - else
              = render position

app/views/positions/new.html.haml
%section#section-new-position
  .container
    .jumbotron
      = render 'form'

app/views/positions/show.html.haml
= render 'position_header'

%section#section-show-position-opinions
  .container
    .row
      .col-sm-12
        - if user_signed_in? && @position.voted?(current_user)

          = form_for [@position, Opinion.new] do |f|
            = f.hidden_field :source_id
            %p.help-block-opinion-choice
              나는 #{choice_icon(@position.voted_by(current_user))} #{@position.voted_by(current_user).choice_text}합니다.
              %a(href="#" data-content="#{render partial: 'votes/change', locals: {position: @position}}" data-placement="right" data-html="true" data-toggle="webui-popover" type="button")
                입장 바꾸기
            %p.help-block-opinion-source.hidden
              @
              %span.nickname
              님의 글에 응답합니다.
              %a(href="#" data-toggle='catan-opinion-cancel-to-respond')
                취소
            .form-group
              = f.text_area :body, placeholder: '의견은...', class: 'form-control'
            = f.submit '의견 남기기', class: 'btn btn-primary btn-sm btn-block'

        %ul.media-list
          - if @position.opinions.best.any?
            %hr
          = render @position.opinions.best
          - if @position.opinions.not_best.any?
            %hr
          = render @position.opinions.not_best