config/routes.rb
Rails.application.routes.draw do
  root to: redirect('http://intro.parti.xyz/')
  sso_devise

  resources :issues do

  end

  resources :positions do
    shallow do
      resources :opinions do
        resources :likes, except: :destory do
          collection do
            delete :by_me, to: 'likes#destroy_by_me'
          end
        end
      end
      resources :votes
    end
  end

  resources :supports do
    collection do
      delete :cancel
    end
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  # relations
  belongs_to :user
  has_many :positions
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource
  respond_to :json, :html

  def show

  end

  def index
    @issues = Issue.where("title like ?", "%#{params[:query]}%" ).limit(10)
    respond_with @issues
  end

  def create
    @issue.user = current_user
    if @issue.save
      redirect_to @issue
    else
      render 'new'
    end
  end

  def update
    if @issue.update(update_params)
      redirect_to @issue
    else
      render 'edit'
    end
  end

  private

  def create_params
    params.require(:issue).permit(:title, :description)
  end

  def update_params
    params.require(:issue).permit(:title, :description)
  end
end

app/views/issues/_form.html.haml
= form_for @issue do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  = f.submit '저장', class: 'btn btn-default'

app/views/issues/_issue.html.haml
%li.list-group-item[issue]
  = link_to issue.title, issue
  = simple_format issue.description

app/views/issues/edit.html.haml
.container
  %h3 수정
  = render 'form'

app/views/issues/index.html.haml
.bs-component
  .container
    - if user_signed_in?
      %p
        = link_to new_issue_path do
          %i.fa.fa-edit
          이슈 만들기

    %section#issues
      %ul.list-group
        = render @issues

app/views/issues/new.html.haml
.container
  %h3 issue 생성
  = render 'form'

app/views/issues/show.html.haml
%section#section-issue-title{ style: 'margin-top: -40px;' }
  .jumbotron
    .container
      .actions.pull-right
        %small
          = link_to '수정', edit_issue_path
      %h2= @issue.title
      %p= simple_format @issue.description

%section#section-issue-news
  .container
    .page-header
      %h3
        뉴스
        %small (0)

%section#section-issue-positions
  .container
    .page-header
      %h3
        투표
        %small (#{@issue.positions.count})
    .row.position-list
      = render @issue.positions

%section#section-issue-canoes
  .container
    .page-header
      %h3
        카누
        %small (0)