config/routes.rb
Rails.application.routes.draw do
  root to: redirect('http://intro.parti.xyz/')
  sso_devise

  resources :issues do

  end

  resources :positions do
    shallow do
      resources :opinions do
        resources :likes, except: :destory do
          collection do
            delete :by_me, to: 'likes#destroy_by_me'
          end
        end
      end
      resources :votes
    end
  end

  resources :supports do
    collection do
      delete :cancel
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include PartiSsoClient::Authentication
  before_action :verify_authentication

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_f(date)
    if date.today?
      date.strftime("%H:%M")
    else
      date.strftime("%Y-%m-%d")
    end
  end

  def user_byline(user)
    return if user.nil?
    raw render(partial: 'users/byline', locals: { user: user })
  end

  def user_byline_tiny(user)
    return if user.nil?
    raw render(partial: 'users/byline_tiny', locals: { user: user })
  end

  def choice_icon(subject)
    choice_value = subject
    choice_value = subject.choice if subject.respond_to?(:choice)
    return if choice_value.nil?
    case choice_value.to_sym
    when :agree
      fa_icon('thumbs-up')
    when :disagree
      fa_icon('thumbs-down')
    end
  end

  def fa_icon(name)
    content_tag(:i, nil, class: "fa fa-#{name}")
  end
end

app/views/application/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: positions_path }
        %strong parti.xyz
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to '이슈', issues_path
        %li
          = link_to '입장? 투표?', positions_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.nickname
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to edit_user_path do
                  %i.fa.fa-pencil-square-o
                  프로필
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %i.fa.fa-sign-out
                  로그아웃
        - else
          %li= link_to '회원가입', sign_up_path
          %li= link_to '로그인', new_user_session_path